#!/usr/bin/env bash

#brew install jq

chmod +x ./localpack
sudo cp ./localpack /usr/local/bin/localpack
chmod +x ./clean-js
sudo cp ./clean-js /usr/local/bin/clean-js
chmod +x ./stop-work
sudo cp ./stop-work /usr/local/bin/stop-work
chmod +x ./orgup
sudo cp ./orgup /usr/local/bin/orgup